### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by FeFoe** [Superexpert/openai-assistant-starter-kit#1]
Hello Stephen,

I want to use parts of your code in an research project at my university.

Under which license can your code be used? I would be happy if you could provide a license, such as the [MIT license](https://choosealicense.com/licenses/mit/).

Best Regards
Felix

**Comment by StephenWalther** [comment]
Hi Felix -- thanks for reaching out!  I just added an explicit MIT license
to the Github repo:

https://github.com/Superexpert/openai-assistant-starter-kit/blob/main/LICENSE

Feedback on the code is always welcomed and appreciated!

Stephen

**Comment by FeFoe** [comment]
Thank you for adding the license!

**Comment by FeFoe** [comment]
Thank you for adding the license!
